"""
Phase 6: Audit query functions.

Retrieve audit trail entries by filters (strategy, date, reason, symbol).
Phase 7 will implement full TimescaleDB queries. For now, Redis retrieval.
"""

from __future__ import annotations

from datetime import datetime
from typing import Any

import structlog

from audit.schema import (
    CircuitBreakerLog,
    RiskDecisionLog,
    SignalLogEntry,
    TradeLogEntry,
)
from data.redis_keys import RedisKeys
from data.store import get_redis

log = structlog.get_logger(__name__)


class AuditQuery:
    """Query audit logs by various filters."""

    @staticmethod
    def get_signals_by_strategy(
        strategy: str,
        since: datetime | None = None,
    ) -> list[SignalLogEntry]:
        """
        Get signals generated by a specific strategy.

        Parameters
        ----------
        strategy : str
            Strategy name to filter by
        since : datetime, optional
            Only return signals after this timestamp

        Returns
        -------
        list[SignalLogEntry]
            Matching signal entries
        """
        try:
            entries = []
            redis = get_redis()
            cursor = 0
            pattern = f"{RedisKeys.AUDIT_SIGNALS}:*"

            while True:
                cursor, keys = redis.scan(cursor, match=pattern, count=100)
                for key in keys:
                    try:
                        data = redis.get(key)
                        if data:
                            entry = SignalLogEntry.model_validate_json(data)
                            if entry.strategy_name == strategy and (
                                since is None or entry.timestamp >= since
                            ):
                                entries.append(entry)
                    except Exception:
                        pass
                if cursor == 0:
                    break

            return sorted(entries, key=lambda x: x.timestamp, reverse=True)
        except Exception as exc:
            log.warning("audit_query_signals_failed", error=str(exc))
            return []

    @staticmethod
    def get_trades_by_date(start_date: datetime, end_date: datetime) -> list[TradeLogEntry]:
        """
        Get all trades within a date range.

        Parameters
        ----------
        start_date : datetime
            Start of date range
        end_date : datetime
            End of date range

        Returns
        -------
        list[TradeLogEntry]
            Matching trade entries
        """
        try:
            entries = []
            redis = get_redis()
            cursor = 0
            pattern = f"{RedisKeys.AUDIT_TRADES}:*"

            while True:
                cursor, keys = redis.scan(cursor, match=pattern, count=100)
                for key in keys:
                    try:
                        data = redis.get(key)
                        if data:
                            entry = TradeLogEntry.model_validate_json(data)
                            if start_date <= entry.timestamp <= end_date:
                                entries.append(entry)
                    except Exception:
                        pass
                if cursor == 0:
                    break

            return sorted(entries, key=lambda x: x.timestamp, reverse=True)
        except Exception as exc:
            log.warning("audit_query_trades_failed", error=str(exc))
            return []

    @staticmethod
    def get_trades_by_symbol(symbol: str) -> list[TradeLogEntry]:
        """
        Get all trades for a specific symbol.

        Parameters
        ----------
        symbol : str
            Trading symbol

        Returns
        -------
        list[TradeLogEntry]
            Matching trade entries
        """
        try:
            entries = []
            redis = get_redis()
            cursor = 0
            pattern = f"{RedisKeys.AUDIT_TRADES}:*"

            while True:
                cursor, keys = redis.scan(cursor, match=pattern, count=100)
                for key in keys:
                    try:
                        data = redis.get(key)
                        if data:
                            entry = TradeLogEntry.model_validate_json(data)
                            if entry.symbol == symbol:
                                entries.append(entry)
                    except Exception:
                        pass
                if cursor == 0:
                    break

            return sorted(entries, key=lambda x: x.timestamp, reverse=True)
        except Exception as exc:
            log.warning("audit_query_trades_by_symbol_failed", error=str(exc))
            return []

    @staticmethod
    def get_risk_decisions_by_reason(reason_filter: str) -> list[RiskDecisionLog]:
        """
        Get risk decisions matching a reason filter.

        Parameters
        ----------
        reason_filter : str
            Substring to match in reason field

        Returns
        -------
        list[RiskDecisionLog]
            Matching risk decision entries
        """
        try:
            entries = []
            redis = get_redis()
            cursor = 0
            pattern = f"{RedisKeys.AUDIT_RISK_DECISIONS}:*"

            while True:
                cursor, keys = redis.scan(cursor, match=pattern, count=100)
                for key in keys:
                    try:
                        data = redis.get(key)
                        if data:
                            entry = RiskDecisionLog.model_validate_json(data)
                            if reason_filter.lower() in entry.reason.lower():
                                entries.append(entry)
                    except Exception:
                        pass
                if cursor == 0:
                    break

            return sorted(entries, key=lambda x: x.timestamp, reverse=True)
        except Exception as exc:
            log.warning("audit_query_risk_decisions_failed", error=str(exc))
            return []

    @staticmethod
    def get_circuit_breaker_events(
        since: datetime | None = None,
    ) -> list[CircuitBreakerLog]:
        """
        Get circuit breaker events.

        Parameters
        ----------
        since : datetime, optional
            Only return events after this timestamp

        Returns
        -------
        list[CircuitBreakerLog]
            Matching circuit breaker events
        """
        try:
            entries = []
            redis = get_redis()
            cursor = 0
            pattern = f"{RedisKeys.AUDIT_CIRCUIT_BREAKER}:*"

            while True:
                cursor, keys = redis.scan(cursor, match=pattern, count=100)
                for key in keys:
                    try:
                        data = redis.get(key)
                        if data:
                            entry = CircuitBreakerLog.model_validate_json(data)
                            if since is None or entry.timestamp >= since:
                                entries.append(entry)
                    except Exception:
                        pass
                if cursor == 0:
                    break

            return sorted(entries, key=lambda x: x.timestamp, reverse=True)
        except Exception as exc:
            log.warning("audit_query_circuit_breaker_failed", error=str(exc))
            return []

    @staticmethod
    def get_recent_signals(limit: int = 100) -> list[SignalLogEntry]:
        """
        Get most recent signals.

        Parameters
        ----------
        limit : int
            Maximum number of signals to return

        Returns
        -------
        list[SignalLogEntry]
            Recent signal entries
        """
        try:
            entries = []
            redis = get_redis()
            cursor = 0
            pattern = f"{RedisKeys.AUDIT_SIGNALS}:*"

            while True:
                cursor, keys = redis.scan(cursor, match=pattern, count=100)
                for key in keys:
                    try:
                        data = redis.get(key)
                        if data:
                            entry = SignalLogEntry.model_validate_json(data)
                            entries.append(entry)
                    except Exception:
                        pass
                if cursor == 0:
                    break

            sorted_entries = sorted(entries, key=lambda x: x.timestamp, reverse=True)
            return sorted_entries[:limit]
        except Exception as exc:
            log.warning("audit_query_recent_signals_failed", error=str(exc))
            return []

    @staticmethod
    def get_signal_statistics(strategy: str | None = None) -> dict[str, Any]:
        """
        Get signal statistics.

        Parameters
        ----------
        strategy : str, optional
            If provided, only compute stats for this strategy

        Returns
        -------
        dict
            Statistics dictionary
        """
        try:
            redis = get_redis()
            cursor = 0
            pattern = f"{RedisKeys.AUDIT_SIGNALS}:*"
            signals: list[SignalLogEntry] = []

            while True:
                cursor, keys = redis.scan(cursor, match=pattern, count=100)
                for key in keys:
                    try:
                        data = redis.get(key)
                        if data:
                            entry = SignalLogEntry.model_validate_json(data)
                            if strategy is None or entry.strategy_name == strategy:
                                signals.append(entry)
                    except Exception:
                        pass
                if cursor == 0:
                    break

            if not signals:
                return {}

            total = len(signals)
            long_signals = sum(1 for s in signals if s.direction == "long")
            short_signals = sum(1 for s in signals if s.direction == "short")
            executed = sum(1 for s in signals if s.mode in ("paper", "live"))
            avg_confidence = sum(s.confidence for s in signals) / total if signals else 0
            avg_score = sum(s.score for s in signals) / total if signals else 0

            return {
                "total": total,
                "long": long_signals,
                "short": short_signals,
                "executed": executed,
                "avg_confidence": avg_confidence,
                "avg_score": avg_score,
                "execution_rate": executed / total if total > 0 else 0,
            }
        except Exception as exc:
            log.warning("audit_signal_statistics_failed", error=str(exc))
            return {}
